---
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone project
        run: git clone https://gitlab.com/openid/conformance-suite.git
