---
name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone project
        run: |
          git clone https://gitlab.com/openid/conformance-suite.git
          ls -ltar conformance-suite
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'
      - name: build
        run: mvn clean package
        working-directory: conformance-suite
      - name: clean up any generated config json
        run: rm -f .gitlab-ci/local-provider-oidcc.plan
        working-directory: conformance-suite
      - name: fetch latest images
        run: docker compose -f ../conformance-suite/docker-compose-localtest.yml pull
        working-directory: conformance-suite
      - name: build local images
        run: docker compose -f ../conformance-suite/docker-compose-localtest.yml build
        working-directory: conformance-suite
      - name: rebuild local containers
        run: docker compose -f ../conformance-suite/docker-compose-localtest.yml up --no-start
        working-directory: conformance-suite
      - name: run test
        run: docker compose -f ../conformance-suite/docker-compose-localtest.yml run test
        working-directory: conformance-suite
