---
name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONFORMANCE_SERVER: https://localhost:8443/
    steps:
      - uses: actions/checkout@v3
      - name: clone project
        run: |
          git clone https://gitlab.com/openid/conformance-suite.git
          ls -ltar conformance-suite
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install httpx
      - name: build
        run: |
          mvn clean package
          rm -f .gitlab-ci/local-provider-oidcc.plan
        working-directory: conformance-suite
      - name: fetch latest images
        run: docker compose -f docker-compose.yml pull
        working-directory: conformance-suite
      - name: build local images
        run: docker compose -f docker-compose.yml build
        working-directory: conformance-suite
      - name: rebuild local containers
        run: docker compose -f docker-compose.yml up -d
        working-directory: conformance-suite
      - name: run test
        run: .gitlab-ci/run-tests.sh --ciba-tests-only
        working-directory: conformance-suite
